{{- if .Values.layout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loom-configuration.fullname" . }}-layout
  labels:
    {{- include "loom-configuration.labels" . | nindent 4 }}
    app.kubernetes.io/component: layout
spec:
  type: {{ .Values.layout.service.type }}
  ports:
    - port: {{ .Values.layout.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "loom-configuration.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: layout
{{- end }}

