apiVersion: v1
kind: Service
metadata:
  name: {{ include "loom-configuration.fullname" . }}
  labels:
    {{- include "loom-configuration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.restPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loom-configuration.selectorLabels" . | nindent 4 }}

